export const CURRENCIES = [
  // ── Major (8) ──────────────────────────────────────────────────────────────
  {code:'INR',flag:'🇮🇳',symbol:'₹',    name:'Indian Rupee',              group:'Major'},
  {code:'USD',flag:'🇺🇸',symbol:'$',    name:'US Dollar',                 group:'Major'},
  {code:'EUR',flag:'🇪🇺',symbol:'€',    name:'Euro',                      group:'Major'},
  {code:'GBP',flag:'🇬🇧',symbol:'£',    name:'British Pound',             group:'Major'},
  {code:'JPY',flag:'🇯🇵',symbol:'¥',    name:'Japanese Yen',              group:'Major'},
  {code:'CHF',flag:'🇨🇭',symbol:'CHF',  name:'Swiss Franc',               group:'Major'},
  {code:'CAD',flag:'🇨🇦',symbol:'C$',   name:'Canadian Dollar',           group:'Major'},
  {code:'AUD',flag:'🇦🇺',symbol:'A$',   name:'Australian Dollar',         group:'Major'},
  // ── Asia-Pacific (22) ──────────────────────────────────────────────────────
  {code:'SGD',flag:'🇸🇬',symbol:'S$',   name:'Singapore Dollar',          group:'Asia-Pacific'},
  {code:'MYR',flag:'🇲🇾',symbol:'RM',   name:'Malaysian Ringgit',         group:'Asia-Pacific'},
  {code:'THB',flag:'🇹🇭',symbol:'฿',    name:'Thai Baht',                 group:'Asia-Pacific'},
  {code:'CNY',flag:'🇨🇳',symbol:'¥',    name:'Chinese Yuan',              group:'Asia-Pacific'},
  {code:'HKD',flag:'🇭🇰',symbol:'HK$',  name:'Hong Kong Dollar',          group:'Asia-Pacific'},
  {code:'KRW',flag:'🇰🇷',symbol:'₩',    name:'South Korean Won',          group:'Asia-Pacific'},
  {code:'TWD',flag:'🇹🇼',symbol:'NT$',  name:'Taiwan Dollar',             group:'Asia-Pacific'},
  {code:'IDR',flag:'🇮🇩',symbol:'Rp',   name:'Indonesian Rupiah',         group:'Asia-Pacific'},
  {code:'PHP',flag:'🇵🇭',symbol:'₱',    name:'Philippine Peso',           group:'Asia-Pacific'},
  {code:'VND',flag:'🇻🇳',symbol:'₫',    name:'Vietnamese Dong',           group:'Asia-Pacific'},
  {code:'BDT',flag:'🇧🇩',symbol:'৳',    name:'Bangladeshi Taka',          group:'Asia-Pacific'},
  {code:'PKR',flag:'🇵🇰',symbol:'₨',    name:'Pakistani Rupee',           group:'Asia-Pacific'},
  {code:'LKR',flag:'🇱🇰',symbol:'Rs',   name:'Sri Lankan Rupee',          group:'Asia-Pacific'},
  {code:'NPR',flag:'🇳🇵',symbol:'Rs',   name:'Nepalese Rupee',            group:'Asia-Pacific'},
  {code:'MMK',flag:'🇲🇲',symbol:'K',    name:'Myanmar Kyat',              group:'Asia-Pacific'},
  {code:'KHR',flag:'🇰🇭',symbol:'៛',    name:'Cambodian Riel',            group:'Asia-Pacific'},
  {code:'LAK',flag:'🇱🇦',symbol:'₭',    name:'Lao Kip',                   group:'Asia-Pacific'},
  {code:'MNT',flag:'🇲🇳',symbol:'₮',    name:'Mongolian Tögrög',          group:'Asia-Pacific'},
  {code:'NZD',flag:'🇳🇿',symbol:'NZ$',  name:'New Zealand Dollar',        group:'Asia-Pacific'},
  {code:'FJD',flag:'🇫🇯',symbol:'FJ$',  name:'Fijian Dollar',             group:'Asia-Pacific'},
  {code:'PGK',flag:'🇵🇬',symbol:'K',    name:'Papua New Guinean Kina',    group:'Asia-Pacific'},
  {code:'BTN',flag:'🇧🇹',symbol:'Nu',   name:'Bhutanese Ngultrum',        group:'Asia-Pacific'},
  // ── Middle East (13) ───────────────────────────────────────────────────────
  {code:'AED',flag:'🇦🇪',symbol:'د.إ',  name:'UAE Dirham',                group:'Middle East'},
  {code:'SAR',flag:'🇸🇦',symbol:'﷼',    name:'Saudi Riyal',               group:'Middle East'},
  {code:'QAR',flag:'🇶🇦',symbol:'﷼',    name:'Qatari Riyal',              group:'Middle East'},
  {code:'TRY',flag:'🇹🇷',symbol:'₺',    name:'Turkish Lira',              group:'Middle East'},
  {code:'KWD',flag:'🇰🇼',symbol:'KD',   name:'Kuwaiti Dinar',             group:'Middle East'},
  {code:'BHD',flag:'🇧🇭',symbol:'BD',   name:'Bahraini Dinar',            group:'Middle East'},
  {code:'OMR',flag:'🇴🇲',symbol:'ر.ع',  name:'Omani Rial',                group:'Middle East'},
  {code:'JOD',flag:'🇯🇴',symbol:'JD',   name:'Jordanian Dinar',           group:'Middle East'},
  {code:'ILS',flag:'🇮🇱',symbol:'₪',    name:'Israeli New Shekel',        group:'Middle East'},
  {code:'IQD',flag:'🇮🇶',symbol:'ع.د',  name:'Iraqi Dinar',               group:'Middle East'},
  {code:'IRR',flag:'🇮🇷',symbol:'﷼',    name:'Iranian Rial',              group:'Middle East'},
  {code:'YER',flag:'🇾🇪',symbol:'﷼',    name:'Yemeni Rial',               group:'Middle East'},
  {code:'LBP',flag:'🇱🇧',symbol:'ل.ل',  name:'Lebanese Pound',            group:'Middle East'},
  // ── Europe (20) ────────────────────────────────────────────────────────────
  {code:'SEK',flag:'🇸🇪',symbol:'kr',   name:'Swedish Krona',             group:'Europe'},
  {code:'NOK',flag:'🇳🇴',symbol:'kr',   name:'Norwegian Krone',           group:'Europe'},
  {code:'DKK',flag:'🇩🇰',symbol:'kr',   name:'Danish Krone',              group:'Europe'},
  {code:'PLN',flag:'🇵🇱',symbol:'zł',   name:'Polish Zloty',              group:'Europe'},
  {code:'RUB',flag:'🇷🇺',symbol:'₽',    name:'Russian Ruble',             group:'Europe'},
  {code:'CZK',flag:'🇨🇿',symbol:'Kč',   name:'Czech Koruna',              group:'Europe'},
  {code:'HUF',flag:'🇭🇺',symbol:'Ft',   name:'Hungarian Forint',          group:'Europe'},
  {code:'RON',flag:'🇷🇴',symbol:'lei',  name:'Romanian Leu',              group:'Europe'},
  {code:'BGN',flag:'🇧🇬',symbol:'лв',   name:'Bulgarian Lev',             group:'Europe'},
  {code:'ALL',flag:'🇦🇱',symbol:'L',    name:'Albanian Lek',              group:'Europe'},
  {code:'MKD',flag:'🇲🇰',symbol:'ден',  name:'Macedonian Denar',          group:'Europe'},
  {code:'RSD',flag:'🇷🇸',symbol:'din',  name:'Serbian Dinar',             group:'Europe'},
  {code:'BAM',flag:'🇧🇦',symbol:'KM',   name:'Bosnia-Herzegovina Mark',   group:'Europe'},
  {code:'ISK',flag:'🇮🇸',symbol:'kr',   name:'Icelandic Króna',           group:'Europe'},
  {code:'UAH',flag:'🇺🇦',symbol:'₴',    name:'Ukrainian Hryvnia',         group:'Europe'},
  {code:'GEL',flag:'🇬🇪',symbol:'₾',    name:'Georgian Lari',             group:'Europe'},
  {code:'AZN',flag:'🇦🇿',symbol:'₼',    name:'Azerbaijani Manat',         group:'Europe'},
  {code:'AMD',flag:'🇦🇲',symbol:'֏',    name:'Armenian Dram',             group:'Europe'},
  {code:'BYN',flag:'🇧🇾',symbol:'Br',   name:'Belarusian Ruble',          group:'Europe'},
  {code:'MDL',flag:'🇲🇩',symbol:'L',    name:'Moldovan Leu',              group:'Europe'},
  // ── Africa (30) ────────────────────────────────────────────────────────────
  {code:'ZAR',flag:'🇿🇦',symbol:'R',    name:'South African Rand',        group:'Africa'},
  {code:'EGP',flag:'🇪🇬',symbol:'E£',   name:'Egyptian Pound',            group:'Africa'},
  {code:'NGN',flag:'🇳🇬',symbol:'₦',    name:'Nigerian Naira',            group:'Africa'},
  {code:'GHS',flag:'🇬🇭',symbol:'GH₵',  name:'Ghanaian Cedi',             group:'Africa'},
  {code:'KES',flag:'🇰🇪',symbol:'KSh',  name:'Kenyan Shilling',           group:'Africa'},
  {code:'ETB',flag:'🇪🇹',symbol:'Br',   name:'Ethiopian Birr',            group:'Africa'},
  {code:'MAD',flag:'🇲🇦',symbol:'MAD',  name:'Moroccan Dirham',           group:'Africa'},
  {code:'TND',flag:'🇹🇳',symbol:'TND',  name:'Tunisian Dinar',            group:'Africa'},
  {code:'DZD',flag:'🇩🇿',symbol:'DA',   name:'Algerian Dinar',            group:'Africa'},
  {code:'LYD',flag:'🇱🇾',symbol:'LD',   name:'Libyan Dinar',              group:'Africa'},
  {code:'SDG',flag:'🇸🇩',symbol:'£',    name:'Sudanese Pound',            group:'Africa'},
  {code:'UGX',flag:'🇺🇬',symbol:'USh',  name:'Ugandan Shilling',          group:'Africa'},
  {code:'TZS',flag:'🇹🇿',symbol:'TSh',  name:'Tanzanian Shilling',        group:'Africa'},
  {code:'ZMW',flag:'🇿🇲',symbol:'ZK',   name:'Zambian Kwacha',            group:'Africa'},
  {code:'MWK',flag:'🇲🇼',symbol:'MK',   name:'Malawian Kwacha',           group:'Africa'},
  {code:'MZN',flag:'🇲🇿',symbol:'MT',   name:'Mozambican Metical',        group:'Africa'},
  {code:'MUR',flag:'🇲🇺',symbol:'₨',    name:'Mauritian Rupee',           group:'Africa'},
  {code:'AOA',flag:'🇦🇴',symbol:'Kz',   name:'Angolan Kwanza',            group:'Africa'},
  {code:'XOF',flag:'🌍',symbol:'CFA',   name:'West African CFA Franc',    group:'Africa'},
  {code:'XAF',flag:'🌍',symbol:'FCFA',  name:'Central African CFA Franc', group:'Africa'},
  {code:'MGA',flag:'🇲🇬',symbol:'Ar',   name:'Malagasy Ariary',           group:'Africa'},
  {code:'RWF',flag:'🇷🇼',symbol:'FRw',  name:'Rwandan Franc',             group:'Africa'},
  {code:'BIF',flag:'🇧🇮',symbol:'FBu',  name:'Burundian Franc',           group:'Africa'},
  {code:'BWP',flag:'🇧🇼',symbol:'P',    name:'Botswana Pula',             group:'Africa'},
  {code:'NAD',flag:'🇳🇦',symbol:'N$',   name:'Namibian Dollar',           group:'Africa'},
  {code:'SCR',flag:'🇸🇨',symbol:'₨',    name:'Seychellois Rupee',         group:'Africa'},
  {code:'GMD',flag:'🇬🇲',symbol:'D',    name:'Gambian Dalasi',            group:'Africa'},
  {code:'SOS',flag:'🇸🇴',symbol:'Sh',   name:'Somali Shilling',           group:'Africa'},
  {code:'GNF',flag:'🇬🇳',symbol:'FG',   name:'Guinean Franc',             group:'Africa'},
  {code:'DJF',flag:'🇩🇯',symbol:'Fdj',  name:'Djiboutian Franc',          group:'Africa'},
  // ── Americas (21) ──────────────────────────────────────────────────────────
  {code:'BRL',flag:'🇧🇷',symbol:'R$',   name:'Brazilian Real',            group:'Americas'},
  {code:'MXN',flag:'🇲🇽',symbol:'$',    name:'Mexican Peso',              group:'Americas'},
  {code:'ARS',flag:'🇦🇷',symbol:'$',    name:'Argentine Peso',            group:'Americas'},
  {code:'CLP',flag:'🇨🇱',symbol:'$',    name:'Chilean Peso',              group:'Americas'},
  {code:'COP',flag:'🇨🇴',symbol:'$',    name:'Colombian Peso',            group:'Americas'},
  {code:'PEN',flag:'🇵🇪',symbol:'S/',   name:'Peruvian Sol',              group:'Americas'},
  {code:'UYU',flag:'🇺🇾',symbol:'$U',   name:'Uruguayan Peso',            group:'Americas'},
  {code:'PYG',flag:'🇵🇾',symbol:'₲',    name:'Paraguayan Guaraní',        group:'Americas'},
  {code:'BOB',flag:'🇧🇴',symbol:'Bs',   name:'Bolivian Boliviano',        group:'Americas'},
  {code:'DOP',flag:'🇩🇴',symbol:'RD$',  name:'Dominican Peso',            group:'Americas'},
  {code:'GTQ',flag:'🇬🇹',symbol:'Q',    name:'Guatemalan Quetzal',        group:'Americas'},
  {code:'HNL',flag:'🇭🇳',symbol:'L',    name:'Honduran Lempira',          group:'Americas'},
  {code:'NIO',flag:'🇳🇮',symbol:'C$',   name:'Nicaraguan Córdoba',        group:'Americas'},
  {code:'CRC',flag:'🇨🇷',symbol:'₡',    name:'Costa Rican Colón',         group:'Americas'},
  {code:'JMD',flag:'🇯🇲',symbol:'J$',   name:'Jamaican Dollar',           group:'Americas'},
  {code:'TTD',flag:'🇹🇹',symbol:'TT$',  name:'Trinidad & Tobago Dollar',  group:'Americas'},
  {code:'BZD',flag:'🇧🇿',symbol:'BZ$',  name:'Belize Dollar',             group:'Americas'},
  {code:'HTG',flag:'🇭🇹',symbol:'G',    name:'Haitian Gourde',            group:'Americas'},
  {code:'GYD',flag:'🇬🇾',symbol:'G$',   name:'Guyanese Dollar',           group:'Americas'},
  {code:'PAB',flag:'🇵🇦',symbol:'B/.',  name:'Panamanian Balboa',         group:'Americas'},
  {code:'BBD',flag:'🇧🇧',symbol:'Bds$', name:'Barbadian Dollar',          group:'Americas'},
  // ── Central Asia (6) ───────────────────────────────────────────────────────
  {code:'AFN',flag:'🇦🇫',symbol:'؋',    name:'Afghan Afghani',            group:'Central Asia'},
  {code:'KZT',flag:'🇰🇿',symbol:'₸',    name:'Kazakhstani Tenge',         group:'Central Asia'},
  {code:'UZS',flag:'🇺🇿',symbol:'сум',  name:'Uzbekistani Som',           group:'Central Asia'},
  {code:'TJS',flag:'🇹🇯',symbol:'SM',   name:'Tajikistani Somoni',        group:'Central Asia'},
  {code:'TMT',flag:'🇹🇲',symbol:'T',    name:'Turkmenistani Manat',       group:'Central Asia'},
  {code:'KGS',flag:'🇰🇬',symbol:'с',    name:'Kyrgyzstani Som',           group:'Central Asia'},
  // ── Alternative Assets (2) ─────────────────────────────────────────────────
  {code:'BTC',flag:'₿',  symbol:'₿',    name:'Bitcoin',                   group:'Alternative Assets'},
  {code:'ETH',flag:'Ξ',  symbol:'Ξ',    name:'Ethereum',                  group:'Alternative Assets'},
]

export const CM = Object.fromEntries(CURRENCIES.map(c => [c.code, c]))

export const CATS = {
  'Food':          { icon: '🍽️', color: '#f97316', subs: ['Groceries','Restaurants','Snacks','Beverages','Sweets','Takeaway'] },
  'Transport':     { icon: '🚗', color: '#3b82f6', subs: ['Fuel','Auto/Cab','Bus/Train','Flight','Parking','Vehicle Maintenance'] },
  'Shopping':      { icon: '🛍️', color: '#8b5cf6', subs: ['Clothes','Electronics','Furniture','Books','Accessories','Appliances'] },
  'Health':        { icon: '💊', color: '#ef4444', subs: ['Medicine','Doctor','Lab Tests','Hospital','Wellness','Dental'] },
  'Entertainment': { icon: '🎬', color: '#ec4899', subs: ['Movies','OTT/Streaming','Gaming','Events','Hobbies','Sports'] },
  'Utilities':     { icon: '💡', color: '#f59e0b', subs: ['Electricity','Water','Gas','Internet','Phone','Cable'] },
  'Housing':       { icon: '🏠', color: '#10b981', subs: ['Rent','EMI','Maintenance','Repairs','Security','Interior'] },
  'Education':     { icon: '📚', color: '#06b6d4', subs: ['Fees','Books','Courses','Stationery','Coaching','Exams'] },
  'Personal':      { icon: '💆', color: '#84cc16', subs: ['Haircut','Skincare','Gym','Spa','Personal Care','Fashion'] },
  'Travel':        { icon: '✈️', color: '#6366f1', subs: ['Hotel','Sightseeing','Visa','Insurance','Souvenirs','Transport'] },
  'Finance':       { icon: '💰', color: '#14b8a6', subs: ['Insurance','Tax','Loan Payment','Investment','Bank Fees','Savings'] },
  'Social':        { icon: '🎉', color: '#f43f5e', subs: ['Gifts','Parties','Donations','Subscriptions','Events','Dining Out'] },
  'Administrative':{ icon: '🗂️', color: '#0ea5e9', subs: ['License Renewal','Passport Renewal','Government Fees','Notary/Legal','Other Govt Fees'] },
  'Other':         { icon: '📌', color: '#94a3b8', subs: ['Miscellaneous','Uncategorized','Refund','Transfer'] },
}

export const VALID_CATS     = Object.keys(CATS)

// 259-colour custom palette (ported from v5)
export const CC = [
  '#ed2a2a','#ed4b2a','#ed6b2a','#ed8c2a','#edac2a','#edcd2a','#eded2a','#cded2a',
  '#aced2a','#8ced2a','#6bed2a','#4bed2a','#2aed2a','#2aed4b','#2aed6b','#2aed8c',
  '#2aedac','#2aedcd','#2aeded','#2acded','#2aaced','#2a8ced','#2a6bed','#2a4bed',
  '#2a2aed','#4b2aed','#6b2aed','#8c2aed','#ac2aed','#cd2aed','#ed2aed','#ed2acd',
  '#ed2aac','#ed2a8c','#ed2a6b','#ed2a4b','#e67474','#e68774','#e69a74','#e6ad74',
  '#e6c074','#e6d374','#e6e674','#d3e674','#c0e674','#ade674','#9ae674','#87e674',
  '#74e674','#74e687','#74e69a','#74e6ad','#74e6c0','#74e6d3','#74e6e6','#74d3e6',
  '#74c0e6','#74ade6','#749ae6','#7487e6','#7474e6','#8774e6','#9a74e6','#ad74e6',
  '#c074e6','#d374e6','#e674e6','#e674d3','#e674c0','#e674ad','#e6749a','#e67487',
  '#b80909','#b82609','#b84309','#b86009','#b87d09','#b89b09','#b8b809','#9bb809',
  '#7db809','#60b809','#43b809','#26b809','#09b809','#09b826','#09b843','#09b860',
  '#09b87d','#09b89b','#09b8b8','#099bb8','#097db8','#0960b8','#0943b8','#0926b8',
  '#0909b8','#2609b8','#4309b8','#6009b8','#7d09b8','#9b09b8','#b809b8','#b8099b',
  '#b8097d','#b80960','#b80943','#b80926','#bf3f3f','#bf553f','#bf6a3f','#bf7f3f',
  '#bf943f','#bfaa3f','#bfbf3f','#a9bf3f','#94bf3f','#7fbf3f','#6abf3f','#55bf3f',
  '#3fbf3f','#3fbf55','#3fbf6a','#3fbf7f','#3fbf94','#3fbfaa','#3fbfbf','#3fa9bf',
  '#3f94bf','#3f7fbf','#3f6abf','#3f55bf','#3f3fbf','#543fbf','#6a3fbf','#7f3fbf',
  '#943fbf','#a93fbf','#bf3fbf','#bf3fa9','#bf3f94','#bf3f7f','#bf3f6a','#bf3f55',
  '#ef0000','#ef2700','#ef4f00','#ef7700','#ef9f00','#efc700','#efef00','#c7ef00',
  '#9fef00','#77ef00','#4fef00','#27ef00','#00ef00','#00ef27','#00ef4f','#00ef77',
  '#00ef9f','#00efc7','#00efef','#00c7ef','#009fef','#0077ef','#004fef','#0027ef',
  '#0000ef','#2700ef','#4f00ef','#7700ef','#9f00ef','#c700ef','#ef00ef','#ef00c7',
  '#ef009f','#ef0077','#ef004f','#ef0027','#e59898','#e5a598','#e5b298','#e5bf98',
  '#e5cc98','#e5d898','#e5e598','#d8e598','#cbe598','#bfe598','#b2e598','#a5e598',
  '#98e598','#98e5a5','#98e5b2','#98e5bf','#98e5cc','#98e5d8','#98e5e5','#98d8e5',
  '#98cbe5','#98bfe5','#98b2e5','#98a5e5','#9898e5','#a598e5','#b298e5','#bf98e5',
  '#cc98e5','#d898e5','#e598e5','#e598d8','#e598cb','#e598bf','#e598b2','#e598a5',
  '#ffffff','#f8fafc','#f1f5f9','#e2e8f0','#d1d5db','#9ca3af','#6b7280','#4b5563',
  '#374151','#1f2937','#111827','#000000','#fef9c3','#fef08a','#fde047','#facc15',
  '#eab308','#ca8a04','#a16207','#854d0e','#dcfce7','#bbf7d0','#86efac','#4ade80',
  '#22c55e','#16a34a','#15803d','#166534','#dbeafe','#bfdbfe','#93c5fd','#60a5fa',
  '#3b82f6','#1d4ed8','#1e40af','#fce7f3','#fbcfe8','#f9a8d4','#f472b6','#ec4899',
  '#db2777','#be185d','#9d174d',
]
// Ground-truth rates as of April 2026 (INR base — 1 INR = X foreign units)
export const FALLBACK_RATES = {
  INR: 1,
  // Major
  USD: 0.01195,  EUR: 0.01104,  GBP: 0.00942,  JPY: 1.7850,
  CHF: 0.01074,  CAD: 0.01659,  AUD: 0.01856,
  // Asia-Pacific
  SGD: 0.01609,  MYR: 0.05283,  THB: 0.41200,  CNY: 0.08670,
  HKD: 0.09310,  KRW: 16.430,   TWD: 0.38500,  IDR: 195.00,
  PHP: 0.67200,  VND: 303.00,   BDT: 1.3150,   PKR: 3.3300,
  LKR: 3.6900,   NPR: 1.5900,   MMK: 25.000,   KHR: 48.600,
  LAK: 263.00,   MNT: 40.700,   NZD: 0.02040,  FJD: 0.02700,
  PGK: 0.04480,  BTN: 1.0000,
  // Middle East
  AED: 0.04388,  SAR: 0.04481,  QAR: 0.04350,  TRY: 0.41000,
  KWD: 0.003673, BHD: 0.004500, OMR: 0.004600, JOD: 0.008476,
  ILS: 0.04440,  IQD: 15.650,   IRR: 503.00,   YER: 2.9930,
  LBP: 1069.0,
  // Europe
  SEK: 0.12360,  NOK: 0.12870,  DKK: 0.07780,  PLN: 0.04840,
  RUB: 1.09500,  CZK: 0.27830,  HUF: 4.3480,   RON: 0.05504,
  BGN: 0.02158,  ALL: 1.1220,   MKD: 0.68000,  RSD: 1.2870,
  BAM: 0.02158,  ISK: 1.6610,   UAH: 0.49500,  GEL: 0.03255,
  AZN: 0.02030,  AMD: 4.6190,   BYN: 0.03917,  MDL: 0.21350,
  // Africa
  ZAR: 0.21780,  EGP: 0.59300,  NGN: 18.570,   GHS: 0.17120,
  KES: 1.5450,   ETB: 1.4400,   MAD: 0.11940,  TND: 0.03724,
  DZD: 1.6110,   LYD: 0.05830,  SDG: 6.6000,   UGX: 44.100,
  TZS: 31.800,   ZMW: 0.32400,  MWK: 20.750,   MZN: 0.76600,
  MUR: 0.55200,  AOA: 10.900,   XOF: 7.2550,   XAF: 7.2550,
  MGA: 53.800,   RWF: 16.800,   BIF: 35.400,   BWP: 0.16380,
  NAD: 0.21780,  SCR: 0.16590,  GMD: 0.79700,  SOS: 6.8100,
  GNF: 103.00,   DJF: 2.1270,
  // Americas
  BRL: 0.06830,  MXN: 0.23700,  ARS: 12.000,   CLP: 11.360,
  COP: 49.500,   PEN: 0.04470,  UYU: 0.50800,  PYG: 90.600,
  BOB: 0.08250,  DOP: 0.71650,  GTQ: 0.09234,  HNL: 0.29440,
  NIO: 0.43790,  CRC: 6.0170,   JMD: 1.8760,   TTD: 0.08116,
  BZD: 0.02410,  HTG: 1.5680,   GYD: 2.4980,   PAB: 0.01195,
  BBD: 0.02390,
  // Central Asia
  AFN: 0.84000,  KZT: 6.0500,   UZS: 153.00,   TJS: 0.13030,
  TMT: 0.04178,  KGS: 1.0400,
}

export const PAY_METHODS    = ['Cash','Credit Card','Debit Card','UPI/QR','Net Banking','Wallet','Cheque','EMI','Other']
export const UPI_APPS       = ['','GPay','PhonePe','Paytm','PayZapp','BHIM','Amazon Pay','WhatsApp Pay','Cred','Slice','Other']
export const WALLET_APPS    = ['','Amazon Pay','Paytm','PhonePe','Mobikwik','Freecharge','Ola Money','Jio Money','Other']
export const INC_SOURCES    = ['Salary','Freelance','Business','Rental','Dividends','Interest','Bonus','Gift','Refund','Side Income','Other']
export const DINING_APPS    = ['','Swiggy','Zomato','Keta','Dineout','EatSure','Blinkit','Zepto','Direct/Self']
export const GROCERY_TAGS   = ['Food','Beverages','Snacks','Dairy','Produce','Meat/Fish','Grains','Condiments','Frozen','Personal Care','Household','Baby/Kids','Pet Food','Bakery','Health/Organic','Other']
export const EXP_TYPES      = ['variable','fixed','luxury','need','want','investment']
export const RECURRING_PERIODS = [
  { val: 'daily',     label: 'Daily' },
  { val: 'weekly',    label: 'Weekly' },
  { val: 'biweekly',  label: 'Bi-weekly' },
  { val: 'monthly',   label: 'Monthly' },
  { val: 'quarterly', label: 'Quarterly' },
  { val: 'yearly',    label: 'Yearly' },
]
